import React, { Component } from 'react';
import Card, { CardActions, CardContent } from 'material-ui/Card';
import Button from 'material-ui/Button';
import Typography from 'material-ui/Typography';
import ComponentWrappers from '../../ComponentWrappers';
import rep from './calender-512.png';

class Welcome extends Component {
  render() {
    return (
      <div>
        <Card
          style={{
            margin: 80,
            width: '18.6%',
            marginLeft: 80,
            display: 'inline-block',
          }}
        >
          <div>
            <img src={rep} alt="Live from space album cover" style={{ width: 250, height: 250 }} />
          </div>
        </Card>

        <Card
          style={{
            margin: 80,
            width: '60%',
            marginLeft: 0,
            display: 'inline-block',
          }}
        >
          <CardContent>
            <Typography type="headline" component="h1">
              Welcome to Timetable Generator
            </Typography>
            <Typography type="body1" color="secondary">
              An IEEE Project
            </Typography>
            <hr />
            <br />
            <Typography component="p">
              Timetable generator capable of auto-generating separate timetable for Teachers and
              Rooms in the Institute based on the Class timetable created/auto-generated by the
              user.
              <br />
              <br />This will allow User to create and modify timetables easily and have them hosted
              online so that they can be retrieved easily.
            </Typography>
          </CardContent>
          <CardActions>
            <Button dense color="accent">
              Get Started
            </Button>
          </CardActions>
        </Card>
      </div>
    );
  }
}

export default ComponentWrappers(Welcome);
